# create a database named habit.db
def create_tables(cur):
    # create a table named habit
    cur.execute("""CREATE TABLE IF NOT EXISTS habit(
    HABIT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    HABIT_NAME TEXT NOT NULL,
    PERIODICITY TEXT NOT NULL CHECK (PERIODICITY IN ('daily', 'weekly')),
    CREATEDDATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATEDDATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    STREAK_COUNT INTEGER);""")

    cur.execute("""CREATE TABLE IF NOT EXISTS completion(
    COMPLETION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    HABIT_ID INTEGER,
    COMPLETED_AT DATETIME,
    FOREIGN KEY (HABIT_ID) REFERENCES habit(HABIT_ID) ON DELETE CASCADE);""")
    return True
